name: Fetch GC Forms Submissions

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_B64: ${{ secrets.PRIVATE_KEY_B64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r python_decryption/requirements.txt

      - name: Run script
        run: python python_decryption/main.py

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update responses.csv with new submissions" || echo "No changes to commit"
          git push

